import discord
from discord.ext import commands
from discord import app_commands
import yt_dlp
import asyncio
from datetime import datetime
import random
import io
from PIL import Image, ImageDraw
from google import genai
import os
from dotenv import load_dotenv

load_dotenv()

DISCORD_TOKEN = os.getenv('DISCORD_TOKEN')
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')
REQUIRED_HOURS_FOR_CERT = 400.0

gemini_client = genai.Client(api_key=GEMINI_API_KEY)

class ERPBot(commands.Bot):
    def __init__(self):
        super().__init__(command_prefix='!', intents=discord.Intents.all())

    async def setup_hook(self):
        await self.add_cog(OnboardingCog(self))
        await self.add_cog(VoiceTrackingCog(self))
        await self.add_cog(AICog(self))
        await self.add_cog(WheelCog(self))
        await self.add_cog(MusicCog(self))
        await self.tree.sync()
        print("Bot is ready and commands are synced!")

class ApplicationModal(discord.ui.Modal, title='Server Registration'):
    is_campus = discord.ui.TextInput(
        label='Are you from Belgium Campus? (Yes/No)',
        placeholder='Yes or No',
        required=True,
        max_length=4
    )
    genre = discord.ui.TextInput(
        label='What is your nickname genre?',
        placeholder='e.g., Household Appliances, Military, Cars',
        required=True,
        max_length=50
    )

    async def on_submit(self, interaction: discord.Interaction):
        await interaction.response.defer(ephemeral=True)
        
        is_bc = self.is_campus.value.strip().lower() in ['yes', 'y', 'yeah']
        user_genre = self.genre.value.strip()
        guild = interaction.guild
        
        role_name = "KomKol" if is_bc else "Kakmerk"
        role = discord.utils.get(guild.roles, name=role_name)
        
        ai_prompt = (
            f"Generate a single, absurd Discord nickname based on this genre: '{user_genre}'. "
            "It MUST sound like a highly specific appliance, vehicle, technical object, or weird item. "
            "Examples of the vibe: 'Hisense 1000W Microwave', 'Cowbell Intensifier 5000', "
            "'Renault Kwid 0.8 STD', 'Zeiss Winkel Microscope'. "
            "Return ONLY the generated name, nothing else. Maximum 30 characters."
        )
        
        try:
            ai_response = gemini_client.models.generate_content(
                model='gemini-3.5-flash',
                contents=ai_prompt
            )
            generated_name = ai_response.text.strip().replace('"', '')
        except Exception:
            generated_name = f"{user_genre[:10]} 3000"
            
        nickname = generated_name[:32]

        if role:
            await interaction.user.add_roles(role)
        
        try:
            await interaction.user.edit(nick=nickname)
            await interaction.followup.send(f"Welcome! You've been assigned the **{role_name}** role and your autogenerated name is **{nickname}**.")
        except discord.Forbidden:
            await interaction.followup.send(f"Welcome! You got the **{role_name}** role. (Note: My bot role is too low to change your nickname to **{nickname}** automatically. Ensure my bot role is higher than yours in the server settings!).")

class OnboardingCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @app_commands.command(name="apply", description="Apply for your server role and autogenerated name")
    async def apply(self, interaction: discord.Interaction):
        await interaction.response.send_modal(ApplicationModal())

class VoiceTrackingCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.active_sessions = {} 
        self.total_time = {}      

    @commands.Cog.listener()
    async def on_voice_state_update(self, member, before, after):

        if before.channel is None and after.channel is not None:
            self.active_sessions[member.id] = datetime.now()
        
        elif before.channel is not None and after.channel is None:
            if member.id in self.active_sessions:
                duration = (datetime.now() - self.active_sessions[member.id]).total_seconds()
                self.total_time[member.id] = self.total_time.get(member.id, 0) + duration
                del self.active_sessions[member.id]

    @app_commands.command(name="certificate", description="Generate a certificate if you have enough VC hours")
    async def get_certificate(self, interaction: discord.Interaction):
        total_seconds = self.total_time.get(interaction.user.id, 0)
        if interaction.user.id in self.active_sessions:
            total_seconds += (datetime.now() - self.active_sessions[interaction.user.id]).total_seconds()
            
        hours = total_seconds / 3600
        
        if hours < REQUIRED_HOURS_FOR_CERT:
            await interaction.response.send_message(f"You only have {hours:.1f}/{REQUIRED_HOURS_FOR_CERT} hours. Keep chatting!", ephemeral=True)
            return

        img = Image.new('RGB', (800, 600), color=(43, 45, 49))
        draw = ImageDraw.Draw(img)
        
        draw.text((250, 150), "CERTIFICATE OF ACTIVITY", fill=(255, 215, 0), font_size=30)
        draw.text((200, 250), f"Awarded to: {interaction.user.display_name}", fill=(255, 255, 255), font_size=40)
        draw.text((280, 400), f"For completing {hours:.1f} hours of VC", fill=(200, 200, 200), font_size=20)
        
        buffer = io.BytesIO()
        img.save(buffer, format='PNG')
        buffer.seek(0)
        
        file = discord.File(buffer, filename="certificate.png")
        await interaction.response.send_message(file=file)

class AICog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @app_commands.command(name="ask", description="Ask the server AI assistant a question")
    async def ask_ai(self, interaction: discord.Interaction, question: str):
        await interaction.response.defer() 
        try:
            response = gemini_client.models.generate_content(
                model='gemini-3.5-flash',
                contents=question
            )
            await interaction.followup.send(response.text[:2000])
        except Exception as e:
            await interaction.followup.send(f"I encountered an error: {e}")

class WheelCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @app_commands.command(name="spin", description="Spin a wheel! Separate options with commas")
    async def spin(self, interaction: discord.Interaction, options: str):
        choices = [choice.strip() for choice in options.split(',') if choice.strip()]
        if len(choices) < 2:
            await interaction.response.send_message("Please provide at least 2 options separated by commas.", ephemeral=True)
            return
            
        result = random.choice(choices)
        await interaction.response.send_message(f"🎡 **Spinning the wheel...**\n\n🎯 The wheel landed on: **{result}**!")

class MusicCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.ytdl_options = {
            'format': 'bestaudio/best',
            'noplaylist': 'True',
            'extractor-args': 'youtube:player_client=android', 
            'quiet': True,
        }
        self.ffmpeg_options = {
            'before_options': '-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5',
            'options': '-vn',
        }
        self.ytdl = yt_dlp.YoutubeDL(self.ytdl_options)

    @app_commands.command(name="play", description="Play audio from a YouTube link")
    async def play(self, interaction: discord.Interaction, url: str):
        if not interaction.user.voice:
            await interaction.response.send_message("You must be in a voice channel first!", ephemeral=True)
            return
            
        await interaction.response.defer()
        
        channel = interaction.user.voice.channel
        voice_client = interaction.guild.voice_client
        
        if not voice_client:
            voice_client = await channel.connect()

        try:
            loop = asyncio.get_event_loop()
            data = await loop.run_in_executor(None, lambda: self.ytdl.extract_info(url, download=False))
            
            song_url = data['url']
            player = discord.FFmpegPCMAudio(song_url, **self.ffmpeg_options)
            
            if voice_client.is_playing():
                voice_client.stop()
                
            voice_client.play(player)
            await interaction.followup.send(f"🎶 Now playing: **{data.get('title')}**")
            
        except Exception as e:
            await interaction.followup.send(f"Could not play the video. YouTube may be blocking the request: {e}")

    @app_commands.command(name="stop", description="Stop the music and leave")
    async def stop(self, interaction: discord.Interaction):
        voice_client = interaction.guild.voice_client
        if voice_client:
            await voice_client.disconnect()
            await interaction.response.send_message("Disconnected.")
        else:
            await interaction.response.send_message("I'm not in a voice channel.", ephemeral=True)

bot = ERPBot()
bot.run(DISCORD_TOKEN)